### ISSUE TITLE
support for version 1.0.0

### ISSUE THREAD

**Issue by zsengineer** [gnuhpc/Kafka-zk-restapi#17]
Is there any view of support for 1.0.0 in the near future? What are the restrictions or obstacles that prevent this being used with kafka version 1.0.0 or higher?

**Comment by tinawenqiao** [comment]
@zsengineer We've already planned to support 1.0. We're working on another project right now, then we will start kafka rest api for 1.0 after accomplishing that. Thanks for your attention.

**Comment by gnuhpc** [comment]
@zsengineer We have supported the Kafka 1.1.1 version already. Please checkout the master branch.
