### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by raphaelauv** [gnuhpc/Kafka-zk-restapi#39]
Hello , maybe someone already wrote a Kafka-zk-restapi dockerFile or even in docker-compose configuration ?

**Comment by gnuhpc** [comment]
@raphaelauv Thanks for your advice. Great idea, and let's see if someone would pr a dockerFile to us.

**Comment by gnuhpc** [comment]
@raphaelauv It has been a long time since we got your advice. Please refer to the pr https://github.com/gnuhpc/Kafka-zk-restapi/pull/48 . Please feel free to reopen this issue if you encounter any problem.
