### ISSUE TITLE
Error path 

### ISSUE THREAD

**Issue by FridMehdi** [gnuhpc/Kafka-zk-restapi#40]
Hello folks :bug:

@gnuhpc  Cannot run the Rest application i get this error do you have any idea  about th issue 
` mvn clean package -Dmaven.test.skip=true `
`k8s@ubuntu:~/Desktop/Kafka-zk-restapi$ bash target/classes/bin/start.sh `
`chmod: cannot access '/home/k8s/Desktop/Kafka-zk-restapi/target/classes/logs': No such file or directory `
`Error: Unable to access jarfile /home/k8s/Desktop/Kafka-zk-restapi/target/classes/lib/kafka*-rest-springboot*.jar `

**Comment by tinawenqiao** [comment]
@FridMehdi  Please extract the tar or zip compiled package and execute bin/start.sh in the directory. Don't execute the script in target/classes/bin/start.sh.  Thanks for your notice, we will update readme about how to run the application.

**Comment by FridMehdi** [comment]
resolved PR https://github.com/gnuhpc/Kafka-zk-restapi/pull/41
