### ISSUE TITLE
Question: rest api deployment 

### ISSUE THREAD

**Issue by FridMehdi** [gnuhpc/Kafka-zk-restapi#42]
hello folks 
My question is about the deployment of the rest api, it should be in the same kafka cluster or we could deploy it externaly in other vm thanks in advavce

**Comment by gnuhpc** [comment]
You should only assure hat the network connection between kafka service (kafka broker and zk)  and this sets of rest apis is without any problems.

That means you could deploy the rest api within the kafka cluster which has always no issues of connectivity. Also, you could deploy it outside of your cluster as long as there is no network connectivity problem.

**Comment by FridMehdi** [comment]
Perfect thanks
