### ISSUE TITLE
Error creating topic with symbols "." and "_" in topic name

### ISSUE THREAD

**Issue by freewms** [gnuhpc/Kafka-zk-restapi#43]
When I try to create a topic named " test.another", I get a response from the API as follows:
```
{
  "test.another": {
    "state": "failure",
    "msg": "Invalid topic name, it contains '.' or '_'.",
    "data": null
  }
}
```
However, when I try to create a topic named "test*another", I get a reply such as:
```
{
  "test*another": {
    "state": "failure",
    "msg": "Topic name \"test*another\" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-'",
    "data": null
  }
}
```
This message contradicts the first. 

Presence of delimiters in the format"."and" _ " is convenient for a large number of topics to combine them into conditional groups.

**Comment by tinawenqiao** [comment]
@freewms  I will fix the problem and unified the message. To validate the topic name, Topic.validate(String topic) is used.  It is an internal function. Kafka does not recommend topic names containing . and _  .

public static void validate(String topic) {
        if (topic.isEmpty())
            throw new InvalidTopicException("Topic name is illegal, it can't be empty");
        if (topic.equals(".") || topic.equals(".."))
            throw new InvalidTopicException("Topic name cannot be \".\" or \"..\"");
        if (topic.length() > MAX_NAME_LENGTH)
            throw new InvalidTopicException("Topic name is illegal, it can't be longer than " + MAX_NAME_LENGTH +
                    " characters, topic name: " + topic);
        if (!containsValidPattern(topic))
            throw new InvalidTopicException("Topic name \"" + topic + "\" is illegal, it contains a character other than " +
                    "ASCII alphanumerics, '.', '_' and '-'");
    }

/**
     * Valid characters for Kafka topics are the ASCII alphanumerics, '.', '_', and '-'
     */
    static boolean containsValidPattern(String topic) {
        for (int i = 0; i < topic.length(); ++i) {
            char c = topic.charAt(i);

            // We don't use Character.isLetterOrDigit(c) because it's slower
            boolean validChar = (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || c == '.' ||
                    c == '_' || c == '-';
            if (!validChar)
                return false;
        }
        return true;
    }

**Comment by tinawenqiao** [comment]
@freewms Thanks for your suggestion. I've fixed the problem. It's allowed to create topic that has . or _ with a warning message _"WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both."_
But if a topic test.another_2 already exists, create test_another_2 is not allowed. It returns error message "Topic 'test_another_2' collides with existing topics: test.another_2".
In order to combine conditional groups, hyphen - is a better choice.

**Comment by gnuhpc** [comment]
@freewms this issue has been fixed. Please pull the latest version from master branch and give it a try. Tell us if any help needed. Thanks!

**Comment by freewms** [comment]
I checked everything. Works! Thank you very much for the prompt response!
