### ISSUE TITLE
remove all pictures of Client from readme

### ISSUE THREAD

**Issue by FridMehdi** [gnuhpc/Kafka-zk-restapi#54]
Hello folks;
could you remove all pictures from readme.md and keep it only on https://github.com/gnuhpc/Kafka-zk-restapi-UI
to have more visibility 
thanks

**Comment by tinawenqiao** [comment]
@FridMehdi Solved the issue. Thanks for your advice.

**Comment by FridMehdi** [comment]
Remove UI screenshots in readme. #55

**Comment by gnuhpc** [comment]
@FridMehdi merged. Thanks for your suggestions!
